/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2025-03-07 05:24:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class products_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1741324994076L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Laptops - LaptopHub</title>\n");
      out.write("    <style>\n");
      out.write("        /* Products Page Styles */\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        body {\n");
      out.write("            background-color: #f5f7fa;\n");
      out.write("            color: #333;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .products-container {\n");
      out.write("            max-width: 1200px;\n");
      out.write("            margin: 2rem auto;\n");
      out.write("            padding: 0 1rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .products-header {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            margin-bottom: 2rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .products-header h1 {\n");
      out.write("            color: #2c3e50;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .filter-sort {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 1rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .filter-sort select {\n");
      out.write("            padding: 0.5rem 1rem;\n");
      out.write("            border: 1px solid #ddd;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            background-color: white;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .sidebar {\n");
      out.write("            width: 250px;\n");
      out.write("            float: left;\n");
      out.write("            padding: 1rem;\n");
      out.write("            background-color: white;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .filter-group {\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .filter-group h3 {\n");
      out.write("            color: #2c3e50;\n");
      out.write("            margin-bottom: 1rem;\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .filter-group ul {\n");
      out.write("            list-style: none;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .filter-group ul li {\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .filter-checkbox {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .filter-checkbox input {\n");
      out.write("            margin-right: 0.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .price-range input {\n");
      out.write("            width: 100%;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .price-inputs {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 0.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .price-inputs input {\n");
      out.write("            width: 45%;\n");
      out.write("            padding: 0.5rem;\n");
      out.write("            border: 1px solid #ddd;\n");
      out.write("            border-radius: 4px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .product-grid {\n");
      out.write("            margin-left: 280px;\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));\n");
      out.write("            gap: 2rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .product-card {\n");
      out.write("            background-color: white;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            overflow: hidden;\n");
      out.write("            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);\n");
      out.write("            transition: transform 0.3s, box-shadow 0.3s;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .product-card:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .product-image {\n");
      out.write("            height: 180px;\n");
      out.write("            overflow: hidden;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            background-color: #f5f7fa;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .product-image img {\n");
      out.write("            max-width: 100%;\n");
      out.write("            max-height: 100%;\n");
      out.write("            object-fit: contain;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .product-details {\n");
      out.write("            padding: 1.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .product-category {\n");
      out.write("            color: #7f8c8d;\n");
      out.write("            font-size: 0.8rem;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .product-title {\n");
      out.write("            color: #2c3e50;\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("            height: 2.6rem;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .product-specs {\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("            color: #7f8c8d;\n");
      out.write("            margin-bottom: 1rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .product-specs span {\n");
      out.write("            display: block;\n");
      out.write("            margin-bottom: 0.2rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .product-price {\n");
      out.write("            font-size: 1.3rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: #2c3e50;\n");
      out.write("            margin-bottom: 1rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .product-price .old-price {\n");
      out.write("            text-decoration: line-through;\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("            color: #7f8c8d;\n");
      out.write("            margin-right: 0.5rem;\n");
      out.write("            font-weight: normal;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .add-to-cart {\n");
      out.write("            display: block;\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 0.8rem;\n");
      out.write("            background-color: #3498db;\n");
      out.write("            color: white;\n");
      out.write("            text-align: center;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: background-color 0.3s;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .add-to-cart:hover {\n");
      out.write("            background-color: #2980b9;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .pagination {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            margin-top: 3rem;\n");
      out.write("            margin-left: 280px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .pagination a {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            width: 40px;\n");
      out.write("            height: 40px;\n");
      out.write("            margin: 0 5px;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            border: 1px solid #ddd;\n");
      out.write("            color: #333;\n");
      out.write("            text-decoration: none;\n");
      out.write("            transition: background-color 0.3s, color 0.3s;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .pagination a.active,\n");
      out.write("        .pagination a:hover {\n");
      out.write("            background-color: #3498db;\n");
      out.write("            color: white;\n");
      out.write("            border-color: #3498db;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        @media (max-width: 992px) {\n");
      out.write("            .sidebar {\n");
      out.write("                width: 100%;\n");
      out.write("                float: none;\n");
      out.write("                margin-bottom: 2rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .product-grid {\n");
      out.write("                margin-left: 0;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .pagination {\n");
      out.write("                margin-left: 0;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        @media (max-width: 576px) {\n");
      out.write("            .product-grid {\n");
      out.write("                grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));\n");
      out.write("                gap: 1rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .products-header {\n");
      out.write("                flex-direction: column;\n");
      out.write("                align-items: flex-start;\n");
      out.write("                gap: 1rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .filter-sort {\n");
      out.write("                width: 100%;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .filter-sort select {\n");
      out.write("                flex: 1;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>LaptopHub - Premium Laptops</title>\n");
      out.write("    <style>\n");
      out.write("        /* Header Styles */\n");
      out.write("        .header {\n");
      out.write("            background-color: #2c3e50;\n");
      out.write("            color: white;\n");
      out.write("            padding: 1rem 2rem;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            box-shadow: 0 2px 5px rgba(0,0,0,0.1);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo {\n");
      out.write("            font-size: 1.8rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: white;\n");
      out.write("            text-decoration: none;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo span {\n");
      out.write("            color: #3498db;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-menu {\n");
      out.write("            display: flex;\n");
      out.write("            list-style: none;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-menu li {\n");
      out.write("            margin-left: 2rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-menu a {\n");
      out.write("            color: white;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: 500;\n");
      out.write("            transition: color 0.3s;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-menu a:hover {\n");
      out.write("            color: #3498db;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .search-cart {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .search-form {\n");
      out.write("            margin-right: 1.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .search-form input {\n");
      out.write("            padding: 0.5rem;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 4px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .cart-icon {\n");
      out.write("            color: white;\n");
      out.write("            font-size: 1.2rem;\n");
      out.write("            text-decoration: none;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .cart-count {\n");
      out.write("            position: absolute;\n");
      out.write("            top: -8px;\n");
      out.write("            right: -8px;\n");
      out.write("            background-color: #e74c3c;\n");
      out.write("            color: white;\n");
      out.write("            font-size: 0.7rem;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            width: 16px;\n");
      out.write("            height: 16px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            .header {\n");
      out.write("                flex-direction: column;\n");
      out.write("                padding: 1rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .nav-menu {\n");
      out.write("                margin-top: 1rem;\n");
      out.write("                flex-wrap: wrap;\n");
      out.write("                justify-content: center;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .nav-menu li {\n");
      out.write("                margin: 0.5rem 1rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .search-cart {\n");
      out.write("                margin-top: 1rem;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <header class=\"header\">\n");
      out.write("        <a href=\"index.jsp\" class=\"logo\">Laptop<span>Hub</span></a>\n");
      out.write("        \n");
      out.write("        <ul class=\"nav-menu\">\n");
      out.write("            <li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("            <li><a href=\"products.jsp\">Laptops</a></li>\n");
      out.write("            <li><a href=\"#\">Deals</a></li>\n");
      out.write("            <li><a href=\"#\">Support</a></li>\n");
      out.write("            <li><a href=\"#\">About Us</a></li>\n");
      out.write("        </ul>\n");
      out.write("        \n");
      out.write("        <div class=\"search-cart\">\n");
      out.write("            <form class=\"search-form\">\n");
      out.write("                <input type=\"text\" placeholder=\"Search laptops...\">\n");
      out.write("            </form>\n");
      out.write("            <a href=\"login.jsp\" class=\"nav-menu-item\">Login</a>\n");
      out.write("            <a href=\"#\" class=\"cart-icon\">🛒\n");
      out.write("                <span class=\"cart-count\">0</span>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </header>");
      out.write("\n");
      out.write("    \n");
      out.write("    <div class=\"products-container\">\n");
      out.write("        <div class=\"products-header\">\n");
      out.write("            <h1>Browse Laptops</h1>\n");
      out.write("            <div class=\"filter-sort\">\n");
      out.write("                <select>\n");
      out.write("                    <option>Sort By</option>\n");
      out.write("                    <option>Price: Low to High</option>\n");
      out.write("                    <option>Price: High to Low</option>\n");
      out.write("                    <option>Best Selling</option>\n");
      out.write("                    <option>New Arrivals</option>\n");
      out.write("                </select>\n");
      out.write("                <select>\n");
      out.write("                    <option>12 per page</option>\n");
      out.write("                    <option>24 per page</option>\n");
      out.write("                    <option>36 per page</option>\n");
      out.write("                </select>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"sidebar\">\n");
      out.write("            <div class=\"filter-group\">\n");
      out.write("                <h3>Categories</h3>\n");
      out.write("                <ul>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"filter-checkbox\">\n");
      out.write("                            <input type=\"checkbox\" id=\"gaming\" name=\"category\">\n");
      out.write("                            <label for=\"gaming\">Gaming Laptops</label>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"filter-checkbox\">\n");
      out.write("                            <input type=\"checkbox\" id=\"business\" name=\"category\">\n");
      out.write("                            <label for=\"business\">Business Laptops</label>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"filter-checkbox\">\n");
      out.write("                            <input type=\"checkbox\" id=\"student\" name=\"category\">\n");
      out.write("                            <label for=\"student\">Student Laptops</label>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"filter-checkbox\">\n");
      out.write("                            <input type=\"checkbox\" id=\"ultrabook\" name=\"category\">\n");
      out.write("                            <label for=\"ultrabook\">Ultrabooks</label>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"filter-group\">\n");
      out.write("                <h3>Brand</h3>\n");
      out.write("                <ul>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"filter-checkbox\">\n");
      out.write("                            <input type=\"checkbox\" id=\"dell\" name=\"brand\">\n");
      out.write("                            <label for=\"dell\">Dell</label>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"filter-checkbox\">\n");
      out.write("                            <input type=\"checkbox\" id=\"hp\" name=\"brand\">\n");
      out.write("                            <label for=\"hp\">HP</label>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"filter-checkbox\">\n");
      out.write("                            <input type=\"checkbox\" id=\"lenovo\" name=\"brand\">\n");
      out.write("                            <label for=\"lenovo\">Lenovo</label>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"filter-checkbox\">\n");
      out.write("                            <input type=\"checkbox\" id=\"apple\" name=\"brand\">\n");
      out.write("                            <label for=\"apple\">Apple</label>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"filter-checkbox\">\n");
      out.write("                            <input type=\"checkbox\" id=\"asus\" name=\"brand\">\n");
      out.write("                            <label for=\"asus\">Asus</label>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"filter-group\">\n");
      out.write("                <h3>Price Range</h3>\n");
      out.write("                <div class=\"price-range\">\n");
      out.write("                    <input type=\"range\" min=\"0\" max=\"5000\" value=\"2500\">\n");
      out.write("                    <div class=\"price-inputs\">\n");
      out.write("                        <input type=\"number\" placeholder=\"Min\" min=\"0\">\n");
      out.write("                        <input type=\"number\" placeholder=\"Max\" min=\"0\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"filter-group\">\n");
      out.write("                <h3>Processor</h3>\n");
      out.write("                <ul>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"filter-checkbox\">\n");
      out.write("                            <input type=\"checkbox\" id=\"intel-i7\" name=\"processor\">\n");
      out.write("                            <label for=\"intel-i7\">Intel Core i7</label>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"filter-checkbox\">\n");
      out.write("                            <input type=\"checkbox\" id=\"intel-i5\" name=\"processor\">\n");
      out.write("                            <label for=\"intel-i5\">Intel Core i5</label>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"filter-checkbox\">\n");
      out.write("                            <input type=\"checkbox\" id=\"amd-ryzen7\" name=\"processor\">\n");
      out.write("                            <label for=\"amd-ryzen7\">AMD Ryzen 7</label>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"filter-checkbox\">\n");
      out.write("                            <input type=\"checkbox\" id=\"amd-ryzen5\" name=\"processor\">\n");
      out.write("                            <label for=\"amd-ryzen5\">AMD Ryzen 5</label>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"filter-group\">\n");
      out.write("                <h3>RAM</h3>\n");
      out.write("                <ul>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"filter-checkbox\">\n");
      out.write("                            <input type=\"checkbox\" id=\"ram-8gb\" name=\"ram\">\n");
      out.write("                            <label for=\"ram-8gb\">8 GB</label>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"filter-checkbox\">\n");
      out.write("                            <input type=\"checkbox\" id=\"ram-16gb\" name=\"ram\">\n");
      out.write("                            <label for=\"ram-16gb\">16 GB</label>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"filter-checkbox\">\n");
      out.write("                            <input type=\"checkbox\" id=\"ram-32gb\" name=\"ram\">\n");
      out.write("                            <label for=\"ram-32gb\">32 GB</label>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"product-grid\">\n");
      out.write("            <!-- Product 1 -->\n");
      out.write("            <div class=\"product-card\">\n");
      out.write("                <div class=\"product-image\">\n");
      out.write("                    <img src=\"/images/laptop1.jpg\" alt=\"Dell XPS 13\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"product-details\">\n");
      out.write("                    <div class=\"product-category\">Ultrabook</div>\n");
      out.write("                    <h3 class=\"product-title\">Dell XPS 13</h3>\n");
      out.write("                    <div class=\"product-specs\">\n");
      out.write("                        <span>Intel Core i7</span>\n");
      out.write("                        <span>16GB RAM</span>\n");
      out.write("                        <span>512GB SSD</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"product-price\">\n");
      out.write("                        <span class=\"old-price\">$1,499</span>\n");
      out.write("                        $1,299\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"#\" class=\"add-to-cart\">Add to Cart</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Product 2 -->\n");
      out.write("            <div class=\"product-card\">\n");
      out.write("                <div class=\"product-image\">\n");
      out.write("                    <img src=\"/images/laptop2.jpg\" alt=\"HP Spectre x360\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"product-details\">\n");
      out.write("                    <div class=\"product-category\">2-in-1</div>\n");
      out.write("                    <h3 class=\"product-title\">HP Spectre x360</h3>\n");
      out.write("                    <div class=\"product-specs\">\n");
      out.write("                        <span>Intel Core i5</span>\n");
      out.write("                        <span>8GB RAM</span>\n");
      out.write("                        <span>256GB SSD</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"product-price\">$1,099</div>\n");
      out.write("                    <a href=\"#\" class=\"add-to-cart\">Add to Cart</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Product 3 -->\n");
      out.write("            <div class=\"product-card\">\n");
      out.write("                <div class=\"product-image\">\n");
      out.write("                    <img src=\"/images/laptop3.jpg\" alt=\"Lenovo Legion 5\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"product-details\">\n");
      out.write("                    <div class=\"product-category\">Gaming</div>\n");
      out.write("                    <h3 class=\"product-title\">Lenovo Legion 5");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
