/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2025-03-17 03:34:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dto.ExamDTO;
import java.util.List;
import dto.UserDTO;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1741758453583L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1742181677834L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("dto.UserDTO");
    _jspx_imports_classes.add("dto.ExamDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Startup Project Management</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Online Examination</title>\n");
      out.write("    <style>\n");
      out.write("        /* Header Styles */\n");
      out.write("        .header {\n");
      out.write("            background-color: #2c3e50;\n");
      out.write("            color: white;\n");
      out.write("            padding: 1rem 2rem;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            box-shadow: 0 2px 5px rgba(0,0,0,0.1);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo {\n");
      out.write("            font-size: 1.8rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: white;\n");
      out.write("            text-decoration: none;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .logo span {\n");
      out.write("            color: #3498db;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-menu {\n");
      out.write("            display: flex;\n");
      out.write("            list-style: none;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-menu li {\n");
      out.write("            margin-left: 2rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-menu a {\n");
      out.write("            color: white;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: 500;\n");
      out.write("            transition: color 0.3s;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .nav-menu a:hover {\n");
      out.write("            color: #3498db;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .search-cart {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .search-form {\n");
      out.write("            margin-right: 1.5rem;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .search-form input {\n");
      out.write("            padding: 0.5rem;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 4px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .cart-icon {\n");
      out.write("            color: white;\n");
      out.write("            font-size: 1.2rem;\n");
      out.write("            text-decoration: none;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .cart-count {\n");
      out.write("            position: absolute;\n");
      out.write("            top: -8px;\n");
      out.write("            right: -8px;\n");
      out.write("            background-color: #e74c3c;\n");
      out.write("            color: white;\n");
      out.write("            font-size: 0.7rem;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            width: 16px;\n");
      out.write("            height: 16px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            .header {\n");
      out.write("                flex-direction: column;\n");
      out.write("                padding: 1rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .nav-menu {\n");
      out.write("                margin-top: 1rem;\n");
      out.write("                flex-wrap: wrap;\n");
      out.write("                justify-content: center;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .nav-menu li {\n");
      out.write("                margin: 0.5rem 1rem;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .search-cart {\n");
      out.write("                margin-top: 1rem;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <header class=\"header\">\n");
      out.write("        <a href=\"index.jsp\" class=\"logo\">Online<span>Examination</span></a>\n");
      out.write("        <div class=\"search-cart\">\n");
      out.write("            <a href=\"login.jsp\" class=\"nav-menu-item\">Login</a>\n");
      out.write("        </div>\n");
      out.write("    </header>");
      out.write("\n");
      out.write("        <div class=\"dashboard-container\">\n");
      out.write("            <h2>Welcome, ");
      out.print( ((UserDTO) session.getAttribute("user")).getUsername());
      out.write("</h2>\n");
      out.write("\n");
      out.write("            ");
 if (((UserDTO) session.getAttribute("user")).getRole().equals("Instructor")) { 
      out.write("\n");
      out.write("            <form action=\"MainController\" method=\"get\">\n");
      out.write("                <a href=\"projectForm.jsp\">\n");
      out.write("                    Add Project\n");
      out.write("                </a>\n");
      out.write("            </form>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <form action=\"MainController\" method=\"get\">\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"searchProjects\">\n");
      out.write("                <input type=\"text\" name=\"txtSearchTerm\" placeholder=\"Search Project Name\">\n");
      out.write("                <button type=\"submit\">Search</button>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("            ");
 if (request.getAttribute("message") != null) {
      out.write("\n");
      out.write("            <div class=\"success\">");
      out.print( request.getAttribute("message"));
      out.write("</div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <table border=\"1\">\n");
      out.write("                <tr>\n");
      out.write("                    <th>Project Name</th>\n");
      out.write("                    <th>Description</th>\n");
      out.write("                    <th>Status</th>\n");
      out.write("                    <th>Estimated Launch</th>\n");
      out.write("                        ");
 if (((UserDTO) session.getAttribute("user")).getRole().equals("Founder")) { 
      out.write("\n");
      out.write("                    <th>Update Status</th>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                </tr>\n");
      out.write("                ");
 List<ExamDTO> exams = (List<ExamDTO>) request.getAttribute("projects");
                    if (exams != null) {
                        for (ExamDTO exam : exams) {
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td>");
      out.print( exam.getExam_title());
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( exam.getSubject());
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( exam.getCategory_id());
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( exam.getTotal_marks());
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( exam.getDuration());
      out.write("</td>\n");
      out.write("                    ");
 if (((UserDTO) session.getAttribute("user")).getRole().equals("Founder")) {
      out.write("\n");
      out.write("                    <td>\n");
      out.write("                        <form action=\"MainController\" method=\"post\">\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"updateProjectStatus\">\n");
      out.write("                            <input type=\"hidden\" name=\"txtProjectId\" value=\"");
      out.print( exam.getExam_id());
      out.write("\">\n");
      out.write("                            <select name=\"txtStatus\">\n");
      out.write("                                <option value=\"Ideation\">Ideation</option>\n");
      out.write("                                <option value=\"Development\">Development</option>\n");
      out.write("                                <option value=\"Launch\">Launch</option>\n");
      out.write("                                <option value=\"Scaling\">Scaling</option>\n");
      out.write("                            </select>\n");
      out.write("                            <button type=\"submit\">Update</button>\n");
      out.write("                        </form>\n");
      out.write("                    </td>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </tr>\n");
      out.write("                ");
 }
                    }
      out.write("\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("        ");
      out.write("\n");
      out.write("<style>\n");
      out.write("    /* Footer Styles */\n");
      out.write("    .footer {\n");
      out.write("        background-color: #2c3e50;\n");
      out.write("        color: #ecf0f1;\n");
      out.write("        padding: 3rem 2rem 2rem;\n");
      out.write("        margin-top: 3rem;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .footer-content {\n");
      out.write("        display: flex;\n");
      out.write("        flex-wrap: wrap;\n");
      out.write("        justify-content: space-between;\n");
      out.write("        max-width: 1200px;\n");
      out.write("        margin: 0 auto;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .footer-section {\n");
      out.write("        flex: 1;\n");
      out.write("        min-width: 200px;\n");
      out.write("        margin-bottom: 2rem;\n");
      out.write("        padding: 0 1rem;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .footer-section h3 {\n");
      out.write("        color: #3498db;\n");
      out.write("        margin-bottom: 1.2rem;\n");
      out.write("        font-size: 1.2rem;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .footer-section ul {\n");
      out.write("        list-style: none;\n");
      out.write("        padding: 0;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .footer-section ul li {\n");
      out.write("        margin-bottom: 0.7rem;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .footer-section a {\n");
      out.write("        color: #ecf0f1;\n");
      out.write("        text-decoration: none;\n");
      out.write("        transition: color 0.3s;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .footer-section a:hover {\n");
      out.write("        color: #3498db;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .footer-section p {\n");
      out.write("        line-height: 1.5;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .social-icons {\n");
      out.write("        display: flex;\n");
      out.write("        margin-top: 1rem;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .social-icons a {\n");
      out.write("        display: flex;\n");
      out.write("        align-items: center;\n");
      out.write("        justify-content: center;\n");
      out.write("        width: 36px;\n");
      out.write("        height: 36px;\n");
      out.write("        border-radius: 50%;\n");
      out.write("        background-color: #34495e;\n");
      out.write("        margin-right: 1rem;\n");
      out.write("        transition: background-color 0.3s;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .social-icons a:hover {\n");
      out.write("        background-color: #3498db;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .newsletter form {\n");
      out.write("        display: flex;\n");
      out.write("        margin-top: 1rem;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .newsletter input {\n");
      out.write("        flex: 1;\n");
      out.write("        padding: 0.7rem;\n");
      out.write("        border: none;\n");
      out.write("        border-radius: 4px 0 0 4px;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .newsletter button {\n");
      out.write("        padding: 0.7rem 1rem;\n");
      out.write("        background-color: #3498db;\n");
      out.write("        color: white;\n");
      out.write("        border: none;\n");
      out.write("        border-radius: 0 4px 4px 0;\n");
      out.write("        cursor: pointer;\n");
      out.write("        transition: background-color 0.3s;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .newsletter button:hover {\n");
      out.write("        background-color: #2980b9;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .footer-bottom {\n");
      out.write("        text-align: center;\n");
      out.write("        padding-top: 2rem;\n");
      out.write("        margin-top: 2rem;\n");
      out.write("        border-top: 1px solid #34495e;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    @media (max-width: 768px) {\n");
      out.write("        .footer-section {\n");
      out.write("            flex: 100%;\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<footer class=\"footer\">\n");
      out.write("    <div class=\"footer-content\">\n");
      out.write("        <div class=\"footer-section\">\n");
      out.write("            <h3>Quick Links</h3>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"products.jsp\">Browse Laptops</a></li>\n");
      out.write("                <li><a href=\"#\">Special Offers</a></li>\n");
      out.write("                <li><a href=\"#\">Business Solutions</a></li>\n");
      out.write("                <li><a href=\"#\">Student Discounts</a></li>\n");
      out.write("                <li><a href=\"#\">Compare Models</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"footer-section\">\n");
      out.write("            <h3>Customer Support</h3>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"#\">Contact Us</a></li>\n");
      out.write("                <li><a href=\"#\">FAQs</a></li>\n");
      out.write("                <li><a href=\"#\">Shipping Information</a></li>\n");
      out.write("                <li><a href=\"#\">Return Policy</a></li>\n");
      out.write("                <li><a href=\"#\">Warranty</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"footer-section\">\n");
      out.write("            <h3>About LaptopHub</h3>\n");
      out.write("            <p>LaptopHub is dedicated to providing premium laptops with excellent customer service and technical support.</p>\n");
      out.write("            <div class=\"social-icons\">\n");
      out.write("                <a href=\"#\">📘</a>\n");
      out.write("                <a href=\"#\">📱</a>\n");
      out.write("                <a href=\"#\">🐦</a>\n");
      out.write("                <a href=\"#\">📸</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"footer-section newsletter\">\n");
      out.write("            <h3>Newsletter</h3>\n");
      out.write("            <p>Subscribe to receive updates on new products and special offers.</p>\n");
      out.write("            <form>\n");
      out.write("                <input type=\"email\" placeholder=\"Your email address\">\n");
      out.write("                <button type=\"submit\">Subscribe</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"footer-bottom\">\n");
      out.write("        <p>&copy; ");
      out.print( new java.util.Date().getYear() + 1900 );
      out.write(" LaptopHub. All rights reserved.</p>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
