/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2025-03-17 03:35:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dto.ProjectDTO;
import java.util.List;
import dto.UserDTO;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1741240506000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1741240464000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("dto.ProjectDTO");
    _jspx_imports_classes.add("dto.UserDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Startup Project Management</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <header>\n");
      out.write("        <style>\n");
      out.write("            .navbar {\n");
      out.write("                background-color: #2c3e50;\n");
      out.write("                padding: 20px;\n");
      out.write("                display: flex;\n");
      out.write("                justify-content: space-between;\n");
      out.write("                align-items: center;\n");
      out.write("                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\n");
      out.write("            }\n");
      out.write("            .logo {\n");
      out.write("                color: #ffffff;\n");
      out.write("                font-weight: bold;\n");
      out.write("                font-size: 24px;\n");
      out.write("            }\n");
      out.write("            nav ul {\n");
      out.write("                list-style: none;\n");
      out.write("                display: flex;\n");
      out.write("                gap: 20px;\n");
      out.write("            }\n");
      out.write("            nav ul li a {\n");
      out.write("                color: #ffffff;\n");
      out.write("                text-decoration: none;\n");
      out.write("                font-weight: bold;\n");
      out.write("            }\n");
      out.write("            nav ul li a:hover {\n");
      out.write("                color: #3498db;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("        <div class=\"navbar\">\n");
      out.write("            <div class=\"logo\">Startup Project Management</div>\n");
      out.write("            <nav>\n");
      out.write("                <ul>\n");
      out.write("                    ");
 if (session.getAttribute("user") != null) { 
      out.write("\n");
      out.write("                    <li><a href=\"MainController?action=logout\">Logout</a></li>\n");
      out.write("                        ");
 }
      out.write("\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("        <div class=\"dashboard-container\">\n");
      out.write("            <h2>Welcome, ");
      out.print( ((UserDTO) session.getAttribute("user")).getName());
      out.write("</h2>\n");
      out.write("\n");
      out.write("            ");
 if (((UserDTO) session.getAttribute("user")).getRole().equals("Founder")) { 
      out.write("\n");
      out.write("            <form action=\"MainController\" method=\"get\">\n");
      out.write("                <a href=\"projectForm.jsp\">\n");
      out.write("                    Add Project\n");
      out.write("                </a>\n");
      out.write("            </form>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <form action=\"MainController\" method=\"get\">\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"searchProjects\">\n");
      out.write("                <input type=\"text\" name=\"txtSearchTerm\" placeholder=\"Search Project Name\">\n");
      out.write("                <button type=\"submit\">Search</button>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("            ");
 if (request.getAttribute("message") != null) {
      out.write("\n");
      out.write("            <div class=\"success\">");
      out.print( request.getAttribute("message"));
      out.write("</div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <table border=\"1\">\n");
      out.write("                <tr>\n");
      out.write("                    <th>Project Name</th>\n");
      out.write("                    <th>Description</th>\n");
      out.write("                    <th>Status</th>\n");
      out.write("                    <th>Estimated Launch</th>\n");
      out.write("                        ");
 if (((UserDTO) session.getAttribute("user")).getRole().equals("Founder")) { 
      out.write("\n");
      out.write("                    <th>Update Status</th>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                </tr>\n");
      out.write("                ");
 List<ProjectDTO> projects = (List<ProjectDTO>) request.getAttribute("projects");
                    if (projects != null) {
                        for (ProjectDTO project : projects) {
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td>");
      out.print( project.getProject_name());
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( project.getDescription());
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( project.getStatus());
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( project.getEstimated_launch());
      out.write("</td>\n");
      out.write("                    ");
 if (((UserDTO) session.getAttribute("user")).getRole().equals("Founder")) {
      out.write("\n");
      out.write("                    <td>\n");
      out.write("                        <form action=\"MainController\" method=\"post\">\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"updateProjectStatus\">\n");
      out.write("                            <input type=\"hidden\" name=\"txtProjectId\" value=\"");
      out.print( project.getProject_id());
      out.write("\">\n");
      out.write("                            <select name=\"txtStatus\">\n");
      out.write("                                <option value=\"Ideation\">Ideation</option>\n");
      out.write("                                <option value=\"Development\">Development</option>\n");
      out.write("                                <option value=\"Launch\">Launch</option>\n");
      out.write("                                <option value=\"Scaling\">Scaling</option>\n");
      out.write("                            </select>\n");
      out.write("                            <button type=\"submit\">Update</button>\n");
      out.write("                        </form>\n");
      out.write("                    </td>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </tr>\n");
      out.write("                ");
 }
                    }
      out.write("\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <style>\n");
      out.write("        .footer-container {\n");
      out.write("            background-color: #2c3e50;\n");
      out.write("            color: white;\n");
      out.write("            text-align: center;\n");
      out.write("            padding: 20px 0;\n");
      out.write("            margin-top: 20px;\n");
      out.write("        }\n");
      out.write("        .footer-container p {\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <footer>\n");
      out.write("        <div class=\"footer-container\">\n");
      out.write("            <p>&copy; 2025 Startup Project Management. All rights reserved.</p>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
